name: Trailing Whitespace Check

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: Trailing Whitespace Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Get changed text files
      id: changed-files
      uses: tj-actions/changed-files@v46.0.5
        with:
          files: |
            **.cs
            **.yml
            **.swsl
            **.json
            **.py
    - name: Check for trailing whitespace
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        has_trailing_whitespace=0
        for file in ${ALL_CHANGED_FILES}; do
          echo "Checking $file"
          if grep -qP '[ \t]+$' "$file"; then
            echo "::error file=$file::Trailing whitespace found"
            has_trailing_whitespace=1
          fi
        done

        if [ "$has_trailing_whitespace" -eq 1 ]; then
          echo "Trailing whitespace detected. We recommend using an IDE to prevent this from happening."
          exit 1
        fi